[package]
name = "pack"
version = "0.1.0"
authors = ["Nika Layzell <nika@thelayzells.com>"]
edition = "2018"

[workspace]
members = [ "pack_macros" ]

[dependencies]
pack_macros = { version = "0.1.0", path = "pack_macros" }
