[package]
name = "ptrpack"
version = "0.1.0"
authors = ["Nika Layzell <nika@thelayzells.com>"]
edition = "2018"

[workspace]
members = [ "ptrpack_macros" ]

[features]
default = ["std"]
std = ["alloc"]
alloc = []

[dependencies]
ptrpack_macros = { version = "0.1.0", path = "ptrpack_macros" }
